name: Package Code

on:
  push:
    branches: 
    - master
    - 'releases/v[0-9].[0-9].[0-9]'
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Linux-specific dependencies
      run: sudo apt-get install build-essential libgtk-3-dev
      if: ${{matrix.os == 'ubuntu-latest'}}

    - name: Update python installation files & install pyinstaller
      run: python -m pip install --upgrade pip wheel setuptools pyinstaller

    - name: Download Ubuntu wxPython build directly
      run: wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.1.1-cp39-cp39-linux_x86_64.whl
      if: ${{matrix.os == 'ubuntu-latest'}}

    - name: Install Ubuntu wxPython wheel
      run: pip install wxPython-4.1.1-cp39-cp39-linux_x86_64.whl
      if: ${{matrix.os == 'ubuntu-latest'}}

    - name: Install general dependencies
      run: pip install -r src/requirements.txt

    - name: Build app with pyinstaller
      run: pyinstaller -y --dist src/dist/${{ matrix.os }}/ --clean -F -n "FPS_Grapher" --noconsole src/fps_2_chart.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: src/dist/${{ matrix.os }}/
  
  release:
    if: |
      startsWith(github.ref, 'refs/heads/release') &&
      github.base_ref == refs/heads/main
      
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3

    - run: |
        cd windows-latest
        zip -r FPS_Grapher_Windows.zip FPS_Grapher.exe

    - run: |
        cd ubuntu-latest
        zip -r FPS_Grapher_Ubuntu.zip FPS_Grapher
    
    - run: |
        cd macos-latest
        zip -r FPS_Grapher_MacOS.zip FPS_Grapher.app 
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: |
          windows-latest/FPS_Grapher_Windows.zip
          ubuntu-latest/FPS_Grapher_Ubuntu.zip
          macos-latest/FPS_Grapher_MacOS.zip 
        bodyFile: "CHANGELOG.md"
        allowUpdates: true
        replacesArtifacts: true
        tag: $version